import type { ExportPayload } from "./exportData";

/** Escape a value for a VBA string literal. */
const q = (value: string) =>
  (value ?? "").replace(/\r?\n/g, " ").replace(/"/g, '""').trim();

/** Data cells use | as separator, so strip any stray pipes. */
const cell = (value: string) => q(value).replace(/\|/g, "/");

/** Emit a template as a sequence of `t = t & "..." & vbCrLf` statements. */
function templateFunction(name: string, template: string): string {
  const lines = (template ?? "").split(/\r?\n/);
  const body = lines
    .map((line) => `    t = t & "${q(line)}" & vbCrLf`)
    .join("\n");
  return `Private Function ${name}() As String
    Dim t As String
${body}
    ${name} = t
End Function`;
}

/** VBA procedures are capped at ~64 KB, so the directory is split in chunks. */
function chunkedLoaders(
  name: string,
  rows: string[],
  perChunk = 120,
): { loaders: string; calls: string } {
  if (rows.length === 0) {
    return {
      loaders: `Private Sub ${name}1(c As Collection)\n    ' no rows\nEnd Sub`,
      calls: `    ${name}1 c`,
    };
  }
  const chunks: string[][] = [];
  for (let i = 0; i < rows.length; i += perChunk) {
    chunks.push(rows.slice(i, i + perChunk));
  }
  const loaders = chunks
    .map(
      (chunk, index) =>
        `Private Sub ${name}${index + 1}(c As Collection)\n${chunk
          .map((row) => `    c.Add "${row}"`)
          .join("\n")}\nEnd Sub`,
    )
    .join("\n\n");
  const calls = chunks
    .map((_, index) => `    ${name}${index + 1} c`)
    .join("\n");
  return { loaders, calls };
}

export function generateVbaModule(payload: ExportPayload): string {
  const flightRows = payload.flights.map(
    (f) =>
      `${cell(f.flightNo)}|${cell(f.origin)}|${cell(f.destination)}|${cell(f.depTime)}|${cell(f.daypart)}`,
  );
  const peopleRows = payload.people.map(
    (p) => `${cell(p.staffNo)}|${cell(p.fullName)}`,
  );
  const reasonRows = payload.reasons.map(
    (r) => `${cell(r.label)}|${cell(r.purposeLine)}`,
  );

  const flightsChunk = chunkedLoaders("LoadFlights", flightRows, 150);
  const peopleChunk = chunkedLoaders("LoadPeople", peopleRows, 120);
  const reasonsChunk = chunkedLoaders("LoadReasons", reasonRows, 60);

  return `Attribute VB_Name = "TicketMailer"
' ======================================================================
'  TICKET & REBOOKING MAIL GENERATOR - Outlook VBA edition
'  Generated by Ticket Mail Studio on ${payload.generatedAt}
'  ${payload.people.length} people | ${payload.flights.length} flights | ${payload.reasons.length} reasons
'
'  QUICK START
'    1. Outlook > ALT+F11 > File > Import File... > TicketMailer.bas
'    2. Back in Outlook press ALT+F8 and run  TicketMail
'    3. Answer the prompts - a ready e-mail opens, check it and press Send.
'
'  MACROS YOU CAN RUN (ALT+F8)
'    TicketMail        - menu: new ticket or rebooking
'    NewTicketMail     - straight to the new-ticket questions
'    RebookMail        - straight to the rebooking questions
'    TicketMailerInfo  - shows how many people/flights are loaded
'
'  ID RULE (used to tell trainees from employees)
'    6 digits starting with 1  -> TRAINEE
'    5 digits                  -> EMPLOYEE
'    6 digits starting with 2  -> EMPLOYEE
'
'  REFRESHING THE NAME LIST WITHOUT RE-IMPORTING
'    Save an updated ID,NAME csv as:
'      %USERPROFILE%\\Documents\\TicketMailerPeople.csv
'    The macro loads that file automatically when it exists.
' ======================================================================
Option Explicit

Private Const CHARGE_CODE As String = "${q(payload.settings.defaultChargeCode)}"
Private Const MAIL_TO As String = "${q(payload.settings.toEmails)}"
Private Const MAIL_CC As String = "${q(payload.settings.ccEmails)}"
Private Const SIGN_OFF As String = "${q(payload.settings.signOff)}"
Private Const SIGNATURE As String = "${q(payload.settings.signature)}"
Private Const CSV_NAME As String = "TicketMailerPeople.csv"

' ----------------------------------------------------------------------
'  EMBEDDED DATA
' ----------------------------------------------------------------------
${flightsChunk.loaders}

Private Function FlightData() As Collection
    Dim c As New Collection
${flightsChunk.calls}
    Set FlightData = c
End Function

${peopleChunk.loaders}

Private Function EmbeddedPeople() As Collection
    Dim c As New Collection
${peopleChunk.calls}
    Set EmbeddedPeople = c
End Function

${reasonsChunk.loaders}

Private Function ReasonData() As Collection
    Dim c As New Collection
${reasonsChunk.calls}
    Set ReasonData = c
End Function

${templateFunction("NewTicketTemplate", payload.settings.newTicketTemplate)}

${templateFunction("RebookTemplate", payload.settings.rebookTemplate)}

Private Function NewTicketSubject() As String
    NewTicketSubject = "${q(payload.settings.newTicketSubject)}"
End Function

Private Function RebookSubject() As String
    RebookSubject = "${q(payload.settings.rebookSubject)}"
End Function

' ----------------------------------------------------------------------
'  PEOPLE - csv in Documents wins, otherwise the embedded list
' ----------------------------------------------------------------------
Private Function CsvPath() As String
    CsvPath = Environ("USERPROFILE") & "\\Documents\\" & CSV_NAME
End Function

Private Function PeopleData() As Collection
    Dim c As New Collection
    Dim csvFile As String, rowText As String, parts() As String
    Dim handle As Integer, idPart As String, namePart As String

    csvFile = CsvPath()
    If Len(Dir(csvFile)) > 0 Then
        On Error GoTo UseEmbedded
        handle = FreeFile
        Open csvFile For Input As #handle
        Do While Not EOF(handle)
            Line Input #handle, rowText
            rowText = Trim(Replace(rowText, Chr(34), ""))
            If Len(rowText) > 0 Then
                If InStr(rowText, ",") > 0 Then
                    parts = Split(rowText, ",")
                ElseIf InStr(rowText, vbTab) > 0 Then
                    parts = Split(rowText, vbTab)
                Else
                    parts = Split(rowText, " ")
                End If
                idPart = Trim(parts(0))
                namePart = ""
                If UBound(parts) >= 1 Then namePart = Trim(Join(SliceArray(parts, 1), " "))
                If IsNumeric(idPart) And Len(namePart) > 0 Then
                    c.Add idPart & "|" & UCase(namePart)
                End If
            End If
        Loop
        Close #handle
        On Error GoTo 0
    End If

UseEmbedded:
    If Err.Number <> 0 Then
        Err.Clear
        Reset
    End If
    If c.Count = 0 Then Set c = EmbeddedPeople()
    Set PeopleData = c
End Function

Private Function SliceArray(arr() As String, ByVal startIndex As Long) As String()
    Dim out() As String, i As Long, n As Long
    n = UBound(arr) - startIndex
    If n < 0 Then
        ReDim out(0 To 0)
        SliceArray = out
        Exit Function
    End If
    ReDim out(0 To n)
    For i = startIndex To UBound(arr)
        out(i - startIndex) = arr(i)
    Next i
    SliceArray = out
End Function

' 6 digits starting with 1 = trainee, 5 digits or 6 starting with 2 = employee
Public Function KindOfId(ByVal idText As String) As String
    Dim t As String
    t = Trim(idText)
    If Not IsNumeric(t) Then
        KindOfId = "unknown"
    ElseIf Len(t) = 6 And Left(t, 1) = "1" Then
        KindOfId = "trainee"
    ElseIf Len(t) = 5 Then
        KindOfId = "employee"
    ElseIf Len(t) = 6 And Left(t, 1) = "2" Then
        KindOfId = "employee"
    Else
        KindOfId = "unknown"
    End If
End Function

Private Function LookupName(ByVal idText As String) As String
    Dim c As Collection, i As Long, parts() As String
    Set c = PeopleData()
    idText = Trim(idText)
    For i = 1 To c.Count
        parts = Split(c(i), "|")
        If Trim(parts(0)) = idText Then
            LookupName = UCase(Trim(parts(1)))
            Exit Function
        End If
    Next i
    LookupName = ""
End Function

' ----------------------------------------------------------------------
'  DATES
' ----------------------------------------------------------------------
Private Function ParseDate(ByVal answer As String) As Date
    Dim t As String
    t = LCase(Trim(answer))
    If t = "" Or t = "t" Or t = "tom" Or t = "tomorrow" Then
        ParseDate = Date + 1
    ElseIf t = "today" Or t = "d" Then
        ParseDate = Date
    ElseIf IsNumeric(t) And Len(t) <= 2 Then
        ParseDate = Date + CLng(t)
    ElseIf InStr(t, "-") > 0 And Len(t) >= 8 Then
        ParseDate = DateSerial(CInt(Split(t, "-")(0)), CInt(Split(t, "-")(1)), CInt(Split(t, "-")(2)))
    Else
        ParseDate = CDate(t)
    End If
End Function

Private Function PrettyDate(ByVal d As Date) As String
    PrettyDate = Format(d, "mmm") & " " & Day(d) & "," & Year(d)
End Function

Private Function DatePhrase(ByVal d As Date) As String
    Dim diff As Long
    diff = DateDiff("d", Date, d)
    If diff = 0 Then
        DatePhrase = "today " & PrettyDate(d)
    ElseIf diff = 1 Then
        DatePhrase = "tomorrow " & PrettyDate(d)
    Else
        DatePhrase = PrettyDate(d)
    End If
End Function

' ----------------------------------------------------------------------
'  PROMPTS
' ----------------------------------------------------------------------
Private Function AskSector() As String
    Dim c As Collection, i As Long, parts() As String
    Dim seen As String, menu As String, list As Collection, key As String
    Dim answer As String

    Set c = FlightData()
    Set list = New Collection
    For i = 1 To c.Count
        parts = Split(c(i), "|")
        key = parts(1) & "-" & parts(2)
        If InStr(seen, "[" & key & "]") = 0 Then
            seen = seen & "[" & key & "]"
            list.Add key
            menu = menu & list.Count & ". " & key & vbCrLf
        End If
    Next i

    answer = Trim(InputBox("Which sector (from - to)?" & vbCrLf & vbCrLf & menu & vbCrLf & _
        "Type the number, or type a sector such as ADD-BJR:", "Step 1 of 5 - Sector", "1"))
    If answer = "" Then
        AskSector = ""
    ElseIf IsNumeric(answer) Then
        If CLng(answer) >= 1 And CLng(answer) <= list.Count Then
            AskSector = list(CLng(answer))
        End If
    Else
        AskSector = UCase(Replace(answer, " ", ""))
    End If
End Function

Private Function AskDaypart() As String
    Dim answer As String
    answer = Trim(InputBox("What time of day?" & vbCrLf & vbCrLf & _
        "1. Morning    (before 12:00)" & vbCrLf & _
        "2. Afternoon  (12:00 - 16:59)" & vbCrLf & _
        "3. Evening    (17:00 onwards)" & vbCrLf & _
        "4. Any time" & vbCrLf, "Step 2 of 5 - Time of day", "1"))
    Select Case answer
        Case "1", "m", "morning": AskDaypart = "morning"
        Case "2", "a", "afternoon": AskDaypart = "afternoon"
        Case "3", "e", "evening": AskDaypart = "evening"
        Case Else: AskDaypart = ""
    End Select
End Function

Private Function AskFlights(ByVal sector As String, ByVal daypart As String) As String
    Dim c As Collection, i As Long, parts() As String
    Dim matches As Collection, menu As String, answer As String, picks() As String, j As Long
    Dim result As String

    Set c = FlightData()
    Set matches = New Collection
    For i = 1 To c.Count
        parts = Split(c(i), "|")
        If UCase(parts(1) & "-" & parts(2)) = sector Then
            If daypart = "" Or LCase(parts(4)) = daypart Then
                matches.Add parts(0)
                menu = menu & matches.Count & ". " & parts(0) & "   dep " & parts(3) & "   (" & parts(4) & ")" & vbCrLf
            End If
        End If
    Next i

    If matches.Count = 0 Then
        AskFlights = Trim(InputBox("No stored flight for " & sector & _
            IIf(daypart = "", "", " in the " & daypart) & "." & vbCrLf & vbCrLf & _
            "Type the flight number(s) yourself, e.g. ET-154 OR ET-174" & vbCrLf & _
            "(or leave blank to send the mail without a flight number):", "Step 3 of 5 - Flights", ""))
        Exit Function
    End If

    answer = Trim(InputBox("Flights on " & sector & ":" & vbCrLf & vbCrLf & menu & vbCrLf & _
        "Type the number you want, or several separated by commas (1,2)." & vbCrLf & _
        "Leave blank for no flight number.", "Step 3 of 5 - Flights", "1"))
    If answer = "" Then Exit Function

    picks = Split(answer, ",")
    For j = LBound(picks) To UBound(picks)
        If IsNumeric(Trim(picks(j))) Then
            If CLng(Trim(picks(j))) >= 1 And CLng(Trim(picks(j))) <= matches.Count Then
                If result <> "" Then result = result & " OR "
                result = result & matches(CLng(Trim(picks(j))))
            End If
        End If
    Next j
    AskFlights = result
End Function

' Returns the numbered passenger block, e.g. "1. 36154 GETNET GEZAHEGN ENGIDA"
Private Function AskPassengers(ByRef names As String, ByRef paxCount As Long) As String
    Dim answer As String, tokens() As String, i As Long, n As Long
    Dim idText As String, personName As String, block As String, missing As String

    answer = Trim(InputBox("ID numbers of the passengers." & vbCrLf & vbCrLf & _
        "Separate them with commas or spaces, e.g." & vbCrLf & _
        "   36154, 104112, 210447" & vbCrLf & vbCrLf & _
        "Names are pulled from your list automatically.", "Step 4 of 5 - Passengers", ""))
    If answer = "" Then
        AskPassengers = ""
        Exit Function
    End If

    answer = Replace(Replace(Replace(answer, vbCrLf, ","), " ", ","), ";", ",")
    tokens = Split(answer, ",")
    For i = LBound(tokens) To UBound(tokens)
        idText = Trim(tokens(i))
        If idText <> "" Then
            personName = LookupName(idText)
            If personName = "" Then
                personName = UCase(Trim(InputBox("ID " & idText & " is not in the list." & vbCrLf & _
                    "Type the full name (or leave blank to skip this ID):", "Name for " & idText, "")))
                If personName = "" Then GoTo NextToken
            End If
            n = n + 1
            block = block & n & ". " & idText & " " & personName & vbCrLf
            If names <> "" Then names = names & ", "
            names = names & personName
            If KindOfId(idText) = "unknown" Then missing = missing & idText & " "
        End If
NextToken:
    Next i

    paxCount = n
    If missing <> "" Then
        MsgBox "Heads up - these IDs do not follow the 5/6 digit rule:" & vbCrLf & missing & vbCrLf & vbCrLf & _
               "They are still included in the mail.", vbInformation, "Check the ID numbers"
    End If
    AskPassengers = block
End Function

Private Function AskTickets(ByRef ticketCount As Long) As String
    Dim answer As String, tokens() As String, i As Long, block As String, n As Long
    answer = Trim(InputBox("Ticket numbers to rebook." & vbCrLf & vbCrLf & _
        "Separate them with commas or spaces, e.g." & vbCrLf & _
        "   0712162366863, 0712156444358", "Step 4 of 5 - Tickets", ""))
    If answer = "" Then Exit Function
    answer = Replace(Replace(Replace(answer, vbCrLf, ","), " ", ","), ";", ",")
    tokens = Split(answer, ",")
    For i = LBound(tokens) To UBound(tokens)
        If Trim(tokens(i)) <> "" Then
            n = n + 1
            block = block & "* " & Trim(tokens(i)) & vbCrLf & vbCrLf
        End If
    Next i
    ticketCount = n
    AskTickets = block
End Function

' ----------------------------------------------------------------------
'  TEMPLATE ENGINE  (same placeholders as the web app)
' ----------------------------------------------------------------------
Private Function SignBlock() As String
    SignBlock = SIGN_OFF
    If SIGNATURE <> "" Then SignBlock = SignBlock & vbCrLf & SIGNATURE
End Function

Private Function Tidy(ByVal text As String) As String
    Do While InStr(text, vbCrLf & vbCrLf & vbCrLf) > 0
        text = Replace(text, vbCrLf & vbCrLf & vbCrLf, vbCrLf & vbCrLf)
    Loop
    Do While Left(text, 2) = vbCrLf
        text = Mid(text, 3)
    Loop
    Do While Right(text, 2) = vbCrLf
        text = Left(text, Len(text) - 2)
    Loop
    Tidy = text
End Function

Private Function FillTemplate(ByVal t As String, ByVal sector As String, ByVal d As Date, _
        ByVal flightsText As String, ByVal daypart As String, ByVal chargeText As String, _
        ByVal paxBlock As String, ByVal ticketBlock As String, ByVal reasonLabel As String, _
        ByVal purposeText As String, ByVal names As String, ByVal itemCount As Long) As String

    Dim origin As String, dest As String, flightsLine As String, flightsPhrase As String
    If InStr(sector, "-") > 0 Then
        origin = Split(sector, "-")(0)
        dest = Split(sector, "-")(1)
    Else
        origin = sector
    End If

    If flightsText <> "" Then
        flightsPhrase = " on " & flightsText
        flightsLine = "Preferred Flight - " & flightsText
        If daypart <> "" Then flightsLine = flightsLine & " (" & daypart & " flight)"
    End If

    purposeText = Replace(purposeText, "{NAMES}", names)
    purposeText = Replace(purposeText, "{COUNT}", CStr(itemCount))
    purposeText = Replace(purposeText, "{SECTOR}", sector)
    purposeText = Replace(purposeText, "{DATE}", PrettyDate(d))

    t = Replace(t, "{CHARGE_CODE}", chargeText)
    t = Replace(t, "{PASSENGERS}", Tidy(paxBlock))
    t = Replace(t, "{TICKETS}", Tidy(ticketBlock))
    t = Replace(t, "{SECTOR_SPACED}", IIf(dest = "", origin, origin & " - " & dest))
    t = Replace(t, "{SECTOR}", sector)
    t = Replace(t, "{ORIGIN}", origin)
    t = Replace(t, "{DESTINATION}", dest)
    t = Replace(t, "{DATE_PHRASE}", DatePhrase(d))
    t = Replace(t, "{DATE}", PrettyDate(d))
    t = Replace(t, "{FLIGHTS_PHRASE}", flightsPhrase)
    t = Replace(t, "{FLIGHTS_LINE}", flightsLine)
    t = Replace(t, "{FLIGHTS}", flightsText)
    t = Replace(t, "{DAYPART}", daypart)
    t = Replace(t, "{REASON}", reasonLabel)
    t = Replace(t, "{PURPOSE}", purposeText)
    t = Replace(t, "{NAMES}", names)
    t = Replace(t, "{COUNT}", CStr(itemCount))
    t = Replace(t, "{REMARKS}", "")
    t = Replace(t, "{SIGNOFF}", SignBlock())
    FillTemplate = Tidy(t)
End Function

Private Sub CreateMail(ByVal subjectText As String, ByVal bodyText As String)
    Dim outlookApp As Object, mail As Object
    On Error Resume Next
    Set outlookApp = Application
    If outlookApp Is Nothing Then Set outlookApp = CreateObject("Outlook.Application")
    On Error GoTo 0
    Set mail = outlookApp.CreateItem(0)
    If MAIL_TO <> "" Then mail.To = MAIL_TO
    If MAIL_CC <> "" Then mail.CC = MAIL_CC
    mail.Subject = subjectText
    mail.Body = bodyText
    mail.Display
End Sub

' ----------------------------------------------------------------------
'  MACROS
' ----------------------------------------------------------------------
Public Sub TicketMail()
    Dim answer As String
    answer = Trim(InputBox("What do you need?" & vbCrLf & vbCrLf & _
        "1. NEW TICKET   (process ticket and charge cc)" & vbCrLf & _
        "2. REBOOKING    (rebook existing ticket numbers)" & vbCrLf, "Ticket Mailer", "1"))
    If answer = "2" Then
        RebookMail
    ElseIf answer = "1" Then
        NewTicketMail
    End If
End Sub

Public Sub NewTicketMail()
    Dim sector As String, daypart As String, flightsText As String
    Dim depDate As Date, answerDate As String
    Dim reasonList As Collection, menu As String, i As Long, answer As String
    Dim parts() As String, reasonLabel As String, purposeText As String
    Dim paxBlock As String, names As String, paxCount As Long
    Dim chargeText As String, bodyText As String, subjectText As String

    sector = AskSector()
    If sector = "" Then Exit Sub
    daypart = AskDaypart()

    answerDate = Trim(InputBox("Departure date." & vbCrLf & vbCrLf & _
        "Type a date as YYYY-MM-DD, or:" & vbCrLf & _
        "   today   /   tomorrow   /   2  (= in 2 days)", "Step 2b - Date", "tomorrow"))
    On Error Resume Next
    depDate = ParseDate(answerDate)
    If Err.Number <> 0 Then
        MsgBox "That date could not be read. Use YYYY-MM-DD.", vbExclamation
        Exit Sub
    End If
    On Error GoTo 0

    flightsText = AskFlights(sector, daypart)

    Set reasonList = ReasonData()
    For i = 1 To reasonList.Count
        parts = Split(reasonList(i), "|")
        menu = menu & i & ". " & parts(0) & vbCrLf
    Next i
    answer = Trim(InputBox("Why is the ticket needed?" & vbCrLf & vbCrLf & menu, "Step 5 of 5 - Reason", "1"))
    If IsNumeric(answer) Then
        If CLng(answer) >= 1 And CLng(answer) <= reasonList.Count Then
            parts = Split(reasonList(CLng(answer)), "|")
            reasonLabel = parts(0)
            If UBound(parts) >= 1 Then purposeText = parts(1)
        End If
    End If

    paxBlock = AskPassengers(names, paxCount)
    If paxBlock = "" Then Exit Sub

    chargeText = Trim(InputBox("Charge cc:", "Charge code", CHARGE_CODE))

    bodyText = FillTemplate(NewTicketTemplate(), sector, depDate, flightsText, daypart, _
        chargeText, paxBlock, "", reasonLabel, purposeText, names, paxCount)
    subjectText = FillTemplate(NewTicketSubject(), sector, depDate, flightsText, daypart, _
        chargeText, "", "", reasonLabel, "", names, paxCount)

    CreateMail subjectText, bodyText
End Sub

Public Sub RebookMail()
    Dim sector As String, daypart As String, flightsText As String
    Dim depDate As Date, answerDate As String
    Dim ticketBlock As String, ticketCount As Long
    Dim bodyText As String, subjectText As String

    sector = AskSector()
    If sector = "" Then Exit Sub
    daypart = AskDaypart()

    answerDate = Trim(InputBox("Rebook for which date?" & vbCrLf & vbCrLf & _
        "Type a date as YYYY-MM-DD, or:" & vbCrLf & _
        "   today   /   tomorrow   /   2  (= in 2 days)", "Step 2b - Date", "tomorrow"))
    On Error Resume Next
    depDate = ParseDate(answerDate)
    If Err.Number <> 0 Then
        MsgBox "That date could not be read. Use YYYY-MM-DD.", vbExclamation
        Exit Sub
    End If
    On Error GoTo 0

    flightsText = AskFlights(sector, daypart)
    ticketBlock = AskTickets(ticketCount)
    If ticketBlock = "" Then Exit Sub

    bodyText = FillTemplate(RebookTemplate(), sector, depDate, flightsText, daypart, _
        CHARGE_CODE, "", ticketBlock, "", "", "", ticketCount)
    subjectText = FillTemplate(RebookSubject(), sector, depDate, flightsText, daypart, _
        CHARGE_CODE, "", "", "", "", "", ticketCount)

    CreateMail subjectText, bodyText
End Sub

Public Sub TicketMailerInfo()
    Dim p As Collection, f As Collection, source As String
    Set p = PeopleData()
    Set f = FlightData()
    If Len(Dir(CsvPath())) > 0 Then
        source = "CSV file: " & CsvPath()
    Else
        source = "the list built into this macro"
    End If
    MsgBox "Ticket Mailer is ready." & vbCrLf & vbCrLf & _
           "People loaded: " & p.Count & vbCrLf & _
           "Flights loaded: " & f.Count & vbCrLf & _
           "Name source: " & source & vbCrLf & vbCrLf & _
           "Run TicketMail to write an e-mail.", vbInformation, "Ticket Mailer"
End Sub
`;
}
